#*******************************************************************************
#In this implementation, I consider a time varying beta, B_t and fit 2 parameters
#, i.e   mu and tau
#*******************************************************************************
library("minpack.lm")

#******************************  functions **********************************
#Function for the fraction of T cells with x divisions at time t; f_t
#Parameters: delta = turn-over rate (per day, h = hayflick limit, 
# n = a hill coefficient, tau = the number of naive T cells generated by the thymus
#per day as a fraction of the total number of current T cells,
# alpha = rate for the exponential decline of thymic T cell output, 
# mu = the average number of cell divisions for cells produced from the thymus, 
# delta = the average T cell turnover per day, 
# beta =  the probability of replication

#list of fixed parameters from literature
prs <- list(
  delta = 0.0015, h=50, n=1, a=1/(33.33*365)
)

#propotion of the T cell population with x no. of divisions at time t
f <- function(x, t, tau, mu, beta, fxdParms=prs) with(fxdParms, {
  d <- 1 - beta - delta
  #sum of f_0's
  sumj0 <- dpois(x, mu) + tau / d *dpois(x, mu)* sum((d*exp(a))^(0:x))
  #  coeffs <- d^(-(1:x))
  sumj_all <- sumj0+sum(sapply(1:x,function(j) 
    d^(-j)*prod(2*beta*(h^n)/(h^n+(x-(1:j))^n))*
      (choose(t,j)*dpois(x - j, mu) + tau/d*dpois(x - j, mu)*
         sum((d*exp(a))^-(0:(x - j))* choose(x - 0:(x - j), j))))
  )
  return(d^(t) * sumj_all)
})

#*****Calculating aging whilst updating B_t at each time step (1 yr steps) *****
prdct <- function(mdl, t, parms, fxdParms){
  diffrce <- (20+(14-length(t))*5)
  prb <- dpois(0:100,parms$mu)
  mylist1 <- list()
  for (i in 1:length(t)){
    mylist2 <- c()
    for(j in 1:length(t[[i]])){
      #updating beta at each time step, i.e after a year
      beta <- (fxdParms$delta-parms$tau*exp(-fxdParms$a*(t[[i]][j] -   diffrce )*365))/
        (1 - 2 * sum(((0:100)^fxdParms$n/((0:100)^fxdParms$n + 
                                            fxdParms$h^fxdParms$n)) * prb))
      #calculating the propotions for all 0...100 cell divisions 
      prb <- sapply(0:100, mdl, t = (t[[i]][j] -   diffrce )*365, parms$tau, parms$mu,
                    beta, fxdParms)
      #calculation immunoscence predictor by normalising the propotions from above
      mylist2[j] <- sum((prb/sum(prb))[50:100])
    }
    mylist1[[i]] <- mylist2 
  }
  return(mylist1)
}

#test
#system.time(b <- prdct(f, tpts,  inits, prs))
#b

bestPrdctns <- function(mdl, t, parms, fxdParms){
  diffrce <- (20+(14-length(t))*5)
  prb <- dpois(0:100,parms$mu)
  propnsList <- list()
  betaList <- list()
  for (i in 1:length(t)){
    mylist2 <- c()
    mylist3 <- c()
    for(j in 1:length(t[[i]])){
      beta <- (fxdParms$delta - parms$tau*exp(-fxdParms$a*(t[[i]][j]-  diffrce )*365))/
        (1 - 2 * sum(((0:100)^fxdParms$n/((0:100)^fxdParms$n + 
                                            fxdParms$h^fxdParms$n)) * prb))
      mylist3[j] <- beta
      #calculating the propotions for all 0...100 cell divisions 
      prb <- sapply(0:100, mdl, t = (t[[i]][j] -   diffrce )*365, parms$tau, parms$mu,
                    beta, fxdParms)
      mylist2[j] <- sum((prb/sum(prb))[50:100])
    }
    propnsList[[i]] <- mylist2 
    betaList[[i]] <- mylist3
  }
  return(list(propnsList,betaList))
}

#calculating the disparity between predictions and observed data
residFun <- function(par, mdl,  observed, t, wghts, fxdParms){
  unWghtdPreds <-  prdct(mdl, t, par, fxdParms)
  prdctns <-  mapply(function(x,y) sum(x * y)/sum(y), unWghtdPreds,wghts)
  resids <- log10(prdctns) - log10(observed)
  return(ifelse(is.nan(resids), 1e6, resids))
}

#********************************* data fitting ******************************
.args <- c("preProcessed/LipCancer_data.rds")

.args <- commandArgs(trailingOnly = TRUE)

#Read in data and extract timepoints and weights
incidenceData <- readRDS(.args)
#incidenceData[nrow(incidenceData),2] <- 89#to make ub for last class = 89
tpts <-  mapply(function(i,j) i:j, incidenceData$Age.lb, incidenceData$Age.ub,
                SIMPLIFY = FALSE)
#extract weight: 4.18 and 0.04 obtained from 
#https://www.census.gov/prod/cen2010/briefs/c2010br-03.pdf
wght <-  mapply(function(i,j) {things <- i:j; ifelse( 
  things<50, 1, 4.18-0.04*(things))},incidenceData$Age.lb, incidenceData$Age.ub,
  SIMPLIFY = FALSE)


#initial values for fitting
inits <- list(mu=44.48019, tau=0.003697389); a <- c(0,0); b <- c(100,1)

obs <- incidenceData$`Rate per 100,000`/max(incidenceData$`Rate per 100,000`)
#fitting after normalising
fit <- nls.lm(par = inits, lower = a, upper = b,
              fn = residFun, mdl = f, fxdParms = prs, observed = obs,
              t = tpts, wghts = wght, control = nls.lm.control(nprint=0,
                                                               ftol = 1e-4))

#predictions using the fitted values
unWghtdPreds <-  bestPrdctns(f, tpts, fit$par, prs)[[1]]
prdctns <-  mapply(function(x,y) sum(x * y)/sum(y), unWghtdPreds,wght)

#**********************************plotting****************************************
cancer <- gsub(".*preProcessed/\\s*|_data.rds*", "", .args)

jpeg(paste0('figures/model3Figs/', cancer,'.jpg'))
age <- incidenceData$Age.ub
logObs <- log10(obs)
preds <- log10(prdctns)
plot(age, logObs,  col = "blue",
     xlab = "Age", ylab = bquote('log'[10]*' Incidence'), main =
       bquote(bold(paste(.(cancer) ," with ",beta[t]))))
lines(age, preds)
#Calculating R^2
Rsquare <- cor(obs,preds); Rsquare^2

#function for calculating the AIC
logL <- function(object, REML = FALSE, ...) { 
  
  res <- object$fvec 
  
  N <- length(res) 
  
  val <-  -N * (log(2 * pi) + 1 - log(N) + log(sum(res^2)))/2 
  
  ## the formula here corresponds to estimating sigma^2. 
  
  attr(val, "df") <- 1L + length(coef(object)) 
  
  attr(val, "nobs") <- attr(val, "nall") <- N 
  
  class(val) <- "logLik" 
  
  val 
  
}

#calculate AICarameters
perfom <- 2 * (length(fit$par) + 1) - 2 * logL(fit)

#anotating the graph
vertSpan <- range(logObs)
least <- vertSpan[1]
space <- (vertSpan[2]-vertSpan[1])/15
#text(70, least + 5*space, paste('\nAIC = ', round(perfom,4), '\nRSS=' , round(fit$deviance,4),  pos = 4)) 
#paste("Mean =", round(MyMean, 1), "\nMedian =", round(MyMedian, 1), "\nStd.Dev =", round(MySd, 1)), pos = 4)

text(70, (least ), cex = 1.2, bquote(paste(tau, '=' , .(round(fit$par$tau,6)))))
text(70, (least + 1.2*space), cex = 1.2, bquote(paste(mu, '=' , .(round(fit$par$mu,4)))))
text(70, (least + 2*space), cex = 1.2, expression(bold('Parameters')))
text(70, (least + 3*space), cex = 1.2, bquote(paste('RSS=' , .(round(fit$deviance,6)))))
text(70, (least + 4*space), cex = 1.2, bquote(paste('R'^2*' = ', .(round(Rsquare^2,5)))))
text(70, (least + 5*space), cex = 1.2, bquote(paste('AIC = ', .(round(perfom,4)))))
text(70, (least + 6*space), cex = 1.2, expression(bold('Performance')))

dev.off()
# fit_results <- list(
#   fit = fit,
#   tpts = tpts,
#   wght = wght
# )
# saveRDS(fit_results, paste0("fits/model3fits/",cancer,".rds"))