#*******************************************************************************
#In this implementation, I assumed a constant beta and  I fitted 2 parameters, 
#i.e beta and  mu, with tau fixed
#*******************************************************************************
library("minpack.lm")
#Function for the fraction of T cells with x divisions at time t; f_t
#Parameters: delta = turn-over rate (per day, h = hayflick limit, 
# n = a hill coefficient, tau = the number of naive T cells generated by the thymus
#per day as a fraction of the total number of current T cells,
# alpha = rate for the exponential decline of thymic T cell output, 
# mu = the average number of cell divisions for cells produced from the thymus, 
# delta = the average T cell turnover per day, 
# beta =  the probability of replication

#list of fixed parameters from literature
prs <- list(
  delta = 0.0015, h=50, n=1, tau=0.0017, a=1/(33.33 *365)#fixed paramaters
)

#proportion of the T cell population with x no. of divisions at time t
f <- function(x, t, beta, mu, parms=prs) with(parms, {
  d <- 1 - beta - delta
  #sum of f_0's
  sumj0 <- dpois(x, mu) + tau / d *dpois(x, mu)* sum((d*exp(a))^(0:-x))
  #  coeffs <- d^(-(1:x))
  sumj_all <-  sumj0 +  sum(sapply(1:x,function(j) 
    d^(-j)*prod(2*beta*(h^n)/(h^n+(x - (1:j))^n))*
      (choose(t,j)*dpois(x - j, mu)+tau/d*dpois(x - j, mu)*
         sum((d*exp(a))^-(0:(x - j))*choose(x - 0:(x - j), j))))
  )
  return(d^(t) * sumj_all)
})

#calculating the immunoscence predictor
getPred <- function(mdl,t, parms, fxdParms){
  diffrce <- (20+(14-length(t))*5)
  prdctns <- sapply(1:length(t), function(i) {
    sapply(1:length(t[[i]]), function(j) {
      coll <- sapply(0:100, mdl, t = (t[[i]][j]-diffrce)*365, parms$beta,parms$mu, 
                     fxdParms)
      #normalising
      f_t <- coll/sum(coll)
      sum(f_t[50:100])})}, simplify = FALSE)
}

#calculating the disparity between predictions and observed data
residFun <- function(par, mdl,  observed, t, wghts, fxdParms){
  unWghtdPreds <- getPred(mdl, t, par, fxdParms)
  prdctns <-  mapply(function(x,y) sum(x * y)/sum(y), unWghtdPreds,wghts)
  resids <- log10(prdctns) - log10(observed)
  return(ifelse(is.nan(resids), 1e6, resids))
}

#********************************* data fitting ******************************
.args <- c("preProcessed/BreastCancer_data.rds")

.args <- commandArgs(trailingOnly = TRUE)

#load the data and calculate the population weights in each class
incidenceData <- readRDS(.args[1])
#incidenceData <- readRDS("preProcessed/StomachCancer_data.rds")
#incidenceData[dim(incidenceData)[1],2] <- 100
tpts <-  mapply(function(i,j) i:j, incidenceData$Age.lb, incidenceData$Age.ub, 
                SIMPLIFY = FALSE)
#extract weight: 4.18 and 0.04 obtained from 
#https://www.census.gov/prod/cen2010/briefs/c2010br-03.pdf
wght <-  mapply(function(i,j) {things <- i:j; ifelse( 
  things<50, 1, 4.18-0.04*(things))},incidenceData$Age.lb, incidenceData$Age.ub, 
  SIMPLIFY = FALSE)

#initial values for fitting
inits <- list(beta=0.00141948,mu=34.5511); a <- c(0,0); b <- c(1,100)

obs <- incidenceData$`Rate per 100,000`/ max(incidenceData$`Rate per 100,000`)
#fitting after normalising
fit <- nls.lm(par = inits, lower = a, upper = b,
              fn = residFun, mdl = f, fxdParms = prs, observed = obs, t = tpts,
              wghts = wght, control = nls.lm.control(nprint=0,  ftol = 1e-4))


#predictions using the fitted values
unWghtdPreds <- getPred(f, tpts, fit$par, prs)
prdctns <-  mapply(function(x,y) sum(x * y)/sum(y), unWghtdPreds,wght)

#saving the fits
#fit_results <- list(
#   fit = fit,
#   tpts = tpts,
#   wght = wght
# )
cancer <- gsub(".*preProcessed/\\s*|_data.rds*", "", .args)

saveRDS(fit, paste0("fits/model1fits/",cancer,".rds")[1])

#function to Calculate the AIC
logL <- function(object, REML = FALSE, ...) { 
  
  res <- object$fvec 
  
  N <- length(res) 
  
  val <-  -N * (log(2 * pi) + 1 - log(N) + log(sum(res^2)))/2 
  
  ## the formula here corresponds to estimating sigma^2. 
  
  attr(val, "df") <- 1L + length(coef(object)) 
  
  attr(val, "nobs") <- attr(val, "nall") <- N 
  
  class(val) <- "logLik" 
  
  val 
  
}

#**********************************plotting****************************************

jpeg(paste0('figures/model1Figs/', cancer,'.jpg'))

age <- incidenceData$Age.ub
logObs <- log10(obs)
preds <- log10(prdctns)
plot(age, logObs,  col = "blue",
     xlab = "Age", ylab = bquote('log'[10]*' Incidence'), 
     main = bquote(bold(paste(.(cancer) ," with ",tau," fixed"))))
lines(age, preds)

#Calculating R^2
Rsquare <- cor(logObs,preds); Rsquare^2

perfom <- 2 * (length(fit$par) + 1) - 2 * logL(fit)

vertSpan <- range(logObs)
least <- vertSpan[1]
space <- (vertSpan[2]-vertSpan[1])/12
#text(70, least + 5*space, paste('\nAIC = ', round(perfom,4), '\nRSS=' , round(fit$deviance,4),  pos = 4)) 
#paste("Mean =", round(MyMean, 1), "\nMedian =", round(MyMedian, 1), "\nStd.Dev =", round(MySd, 1)), pos = 4)
text(70, (least + 0), cex = 1.2, bquote(paste(beta, '=' , .(round(fit$par$beta,6)))))
text(70, (least + 1*space), cex = 1.2, bquote(paste(mu, '=' , .(round(fit$par$mu,4)))))
text(70, (least + 2*space), cex = 1.2, expression(bold('Parameters')))
text(70, (least + 3*space), cex = 1.2, bquote(paste('RSS=' , .(round(fit$deviance,6)))))
text(70, (least + 4*space), cex = 1.2, bquote(paste('R'^2*' = ', .(round(Rsquare^2,5)))))
text(70, (least + 5*space), cex = 1.2, bquote(paste('AIC = ', .(round(perfom,4)))))
text(70, (least + 6*space), cex = 1.2, expression(bold('Performance')))

dev.off()
#saveRDS(fit, paste0("fits/model1fits/",cancer,".rds"))
