#*******************************************************************************
#In this implementation, I consider a time varying beta, i.e B_t, and fit 3 
#parameters i.e   mu (lambda), delta and tau
#*******************************************************************************
library("minpack.lm")
library(lhs)
library(parallel)
#******************************  functions **********************************
#Function for the fraction of T cells with x divisions at time t; f_t
#Parameters: delta = turn-over rate (per day), h = hayflick limit, 
# n = a hill coefficient, 
# tau = the number of naive T cells generated by the thymus per day as a 
# fraction of the total number of current T cells,
# alpha = rate for the exponential decline of thymic T cell output, 
# mu = the average number of cell divisions for cells produced from the thymus, 
# delta = the average T cell turnover per day, 
# beta =  the probability of replication

#list of fixed parameters from literature
prs <- list(
  h=50, n=1, a=1/(33.33*365)#delta = 0.001, 
)

#proportion of the T cell population with x no. of divisions at time t
f <- function(x, t, tau, mu, beta, delta, fxdParms=prs) with(fxdParms, {
  d <- 1 - beta - delta
  #sum of f_0's
  sumj0 <- dpois(x, mu) + tau / d *dpois(x, mu)* sum((d*exp(a))^(0:x))
  #  coeffs <- d^(-(1:x))
  sumj_all <- sumj0+sum(sapply(1:x,function(j) 
    d^(-j)*prod(2*beta*(h^n)/(h^n+(x-(1:j))^n))*
      (choose(t,j)*dpois(x - j, mu) + tau/d*dpois(x - j, mu)*
         sum((d*exp(a))^-(0:(x - j))* choose(x - 0:(x - j), j))))
  )
  return(d^(t) * sumj_all)
})

#*****Calculating aging whilst updating B_t at each time step (1 yr steps) *****
getPred <- function(mdl, t, parms, fxdParms){
  #diffrce <- (20+(14-length(t))*5)
  beta <- parms$delta
  #prb <- dpois(0:100,parms$mu)
  mylist1 <- list()
  for (i in 1:length(t)){
    mylist2 <- c()
    for(j in 1:length(t[[i]])){
      #calculating the propotions for all 0...100 cell divisions 
      prb <- sapply(0:100, mdl, t = t[[i]][j], parms$tau, parms$mu,
                    beta, parms$delta, fxdParms)
      #updating beta at each time step, i.e after a year
      n <- fxdParms$n
      beta <- (parms$delta-parms$tau*exp(-fxdParms$a*t[[i]][j]))/
        (1 - 2 * sum(1/(1 + (fxdParms$h/(0:100))^n) * prb))
      #calculation immunoscence predictor by normalising the propotions from above
      mylist2[j] <- sum((prb/sum(prb))[50:100])
    }
    mylist1[[i]] <- mylist2 
  }
  return(mylist1)
}

#test
#inits <- list(mu=33.8672, tau=0.0011, delta = 0.00336) 
#system.time(b <- getPred(f, tpts,  inits, prs))
#unlist(lapply(b, mean))
#b

bestPrdctns <- function(mdl, t, parms, fxdParms){
  #diffrce <- (20+(14-length(t))*5)
  #prb <- dpois(0:100,parms$mu)
  beta <- parms$delta
  propnsList <- list()
  betaList <- list()
  for (i in 1:length(t)){
    mylist2 <- c()
    mylist3 <- c()
    for(j in 1:length(t[[i]])){
      mylist3[j] <- beta
      #calculating the propotions for all 0...100 cell divisions 
      prb <- sapply(0:100, f, t = t[[i]][j], parms$tau, parms$mu,
                    beta, parms$delta, fxdParms)
      n <- fxdParms$n
      beta <- (parms$delta-parms$tau*exp(-fxdParms$a*t[[i]][j]))/
        (1 - 2 * sum(1/(1 + (fxdParms$h/(0:100))^n) * prb))
      mylist2[j] <- sum((prb/sum(prb))[50:100])
    }
    propnsList[[i]] <- mylist2 
    betaList[[i]] <- mylist3
  }
  return(list(propnsList,betaList))
}
#system.time(b2 <- bestPrdctns(f, tpts,  inits, prs))

#calculating the disparity between predictions and observed data
residFun <- function(par, mdl,  observed, t, wghts, fxdParms){
  prdctns <-  getPred(mdl, t, par, fxdParms)
  #prdctns <-  mapply(function(x,y) sum(x * y)/sum(y), unWghtdPreds,wghts)
  resids <- log(unlist(lapply(prdctns, mean))) - log(observed)
  return(ifelse(is.nan(resids), 1e6, resids))
}

#function to Calculate the AIC
logL <- function(object, REML = FALSE, ...) { 
  
  res <- object$fvec 
  
  N <- length(res) 
  
  val <-  -N * (log(2 * pi) + 1 - log(N) + log(sum(res^2)))/2 
  
  ## the formula here corresponds to estimating sigma^2. 
  
  attr(val, "df") <- 1L + length(coef(object)) 
  
  attr(val, "nobs") <- attr(val, "nall") <- N 
  
  class(val) <- "logLik" 
  
  val 
  
}


#fitting after normalising
fitter <- function(i){
  fit <- minpack.lm::nls.lm(par = as.list(Y[i,]), lower = a, upper = b,
                            fn = residFun, mdl = f, fxdParms = prs, 
                            observed = obs, t = tpts, 
                            control = minpack.lm::nls.lm.control(nprint=0,  
                                                                 ftol = 1e-2))
}
#********************************* data fitting ******************************
.args <- c("preProcessed/Mesothelioma_data.rds")

.args <- commandArgs(trailingOnly = TRUE)

#load the data and calculate the population weights in each class
FittedData <- readRDS(.args[1])
cancer <- gsub(".*preProcessed/\\s*|_data.rds*", "", .args)
cancer <- gsub("([a-z])([A-Z])", "\\1 \\2", cancer)
jug <- FittedData$x
lu <- jug -1
FittedData$lb <- (lu-lu[1])*365+365/12
FittedData$ub <- (jug-lu[1])*365

tpts <-  mapply(function(i,j) seq(i,j,365/12), FittedData$lb, FittedData$ub, 
                SIMPLIFY = FALSE)
#extract weight: 4.18 and 0.04 obtained from 
#https://www.census.gov/prod/cen2010/briefs/c2010br-03.pdf
# wght <-  mapply(function(i,j) {things <- i:j; ifelse( 
#   things<50, 1, 4.18-0.04*(things))},FittedData$lb, FittedData$ub, 
#   SIMPLIFY = FALSE)
a <- c(0,1e-7,0.0005); b <- c(100,1, 1)
obs <- FittedData$y/ max(FittedData$y)

# #initial values for fitting
inits <- list(mu=30.1327, tau=0.002199, delta = 0.0013); a <- c(0,1e-7,1e-7); b <- c(100,1, 1)

#fitting after normalising
system.time(fit <- nls.lm(par = inits, lower = a, upper = b,
                          fn = residFun, mdl = f, fxdParms = prs, observed = obs, t = tpts,
                          control = nls.lm.control(nprint=1,  ftol = 1e-2)))

#predictions using the fitted values
prdctns1 <-  bestPrdctns(f, tpts, fit$par, prs)
prdctns <- unlist(lapply(prdctns1[[1]], mean))
#prdctns <-  mapply(function(x,y) sum(x * y)/sum(y), unWghtdPreds[[1]],wght)

#Calculating R^2
Rsquare <- (cor(log(obs),log(prdctns)))^2

#Calculating AIC
perfom <- 2 * (length(fit$par) + 1) - 2 * logL(fit)

fitResults <- c(delta = fit$par$delta, mu = fit$par$mu, tau = fit$par$tau, AIC = perfom, Rsqr = Rsquare)

saveRDS(fitResults, paste0("fits/model3fits/",cancer,".rds")[1])

jpeg(paste0('figures/model3Figs/', cancer,'.jpg'))
#setEPS()
#postscript(paste0('figures/pub/model3Figs/', cancer,'.eps'))
age <- FittedData$x
logObs <- log10(obs)
preds <- log10(prdctns)
plot(age, logObs,  col = "blue",
       xlab = "Age", ylab = bquote('log'[10]*' Incidence'),type = "p",pch =17,
     main = bquote(.(cancer))) #bquote(bold(paste(.(cancer) ," with ",beta[t])))
lines(age, preds, col = "red", lwd = 3)

#anotating the graph
vertSpan <- range(logObs)
least <- vertSpan[1]
space <- (vertSpan[2]-vertSpan[1])/15
text(70, (least ), cex = 1.2, bquote(paste(tau, '=' , .(round(fit$par$tau,6)))))
text(70, (least + 1*space), cex = 1.2, bquote(paste(mu, '=' , .(round(fit$par$mu,4)))))
text(70, (least + 2*space), cex = 1.2, bquote(paste(delta, '=' , .(round(fit$par$delta,4)))))
text(70, (least + 3*space), cex = 1.2, expression(bold('Parameters')))
text(70, (least + 4*space), cex = 1.2, bquote(paste('RSS=' , .(round(fit$deviance,6)))))
text(70, (least + 5*space), cex = 1.2, bquote(paste('R'^2*' = ', .(round(Rsquare^2,5)))))
text(70, (least + 6*space), cex = 1.2, bquote(paste('AIC = ', .(round(perfom,4)))))
text(70, (least + 7*space), cex = 1.2, expression(bold('Performance')))

dev.off()