#*******************************************************************************
#In this implementation, I consider a time varying beta, i.e B_t, and fit 3 parameters
#, i.e   mu, delta and tau
#*******************************************************************************
library("minpack.lm")

#******************************  functions **********************************
#Function for the fraction of T cells with x divisions at time t; f_t
#Parameters: delta = turn-over rate (per day, h = hayflick limit, 
# n = a hill coefficient, tau = the number of naive T cells generated by the thymus
#per day as a fraction of the total number of current T cells,
# alpha = rate for the exponential decline of thymic T cell output, 
# mu = the average number of cell divisions for cells produced from the thymus, 
# delta = the average T cell turnover per day, 
# beta =  the probability of replication

#list of fixed parameters from literature
prs <- list(
  h=50, n=1, a=1/(33.33)#delta = 0.001, 
)

#proportion of the T cell population with x no. of divisions at time t
f <- function(x, t, tau, mu, beta, delta, fxdParms=prs) with(fxdParms, {
  d <- 1 - beta - delta
  #sum of f_0's
  sumj0 <- dpois(x, mu) + tau / d *dpois(x, mu)* sum((d*exp(a))^(0:x))
  #  coeffs <- d^(-(1:x))
  sumj_all <- sumj0+sum(sapply(1:x,function(j) 
    d^(-j)*prod(2*beta*(h^n)/(h^n+(x-(1:j))^n))*
      (choose(t,j)*dpois(x - j, mu) + tau/d*dpois(x - j, mu)*
         sum((d*exp(a))^-(0:(x - j))* choose(x - 0:(x - j), j))))
  )
  return(d^(t) * sumj_all)
})

#*****Calculating aging whilst updating B_t at each time step (1 yr steps) *****
getPred <- function(mdl, t, parms, fxdParms){
  t <- (t-min(t))*365
  beta <- parms$delta
  #prb <- dpois(0:100,parms$mu)
  mylist2 <- c()
  for(j in 1:length(t)){
    #calculating the propotions for all 0...100 cell divisions 
    prb <- sapply(0:100, mdl, t = t[j], parms$tau, parms$mu,
                  beta, parms$delta, fxdParms)
    #updating beta at each time step, i.e after a year
    beta <- (parms$delta-parms$tau*exp(-fxdParms$a*t[j]))/
      (1 - 2 * sum(((0:100)^fxdParms$n/((0:100)^fxdParms$n + 
                                          fxdParms$h^fxdParms$n)) * prb))
    #calculation immunoscence predictor by normalising the propotions from above
    mylist2[j] <- sum((prb/sum(prb))[50:100])
  }
  return(mylist2)
}

#test
#system.time(b <- getPred(f, tpts,  inits, prs))
#b

#calculating the disparity between predictions and observed data
residFun <- function(par, mdl,  observed, t, wghts, fxdParms){
  prdctns <- getPred(mdl, t, par, fxdParms)
  resids <- log(prdctns) - log(observed)
  return(ifelse(is.nan(resids), 1e6, resids))
}

#function to Calculate the AIC
logL <- function(object, REML = FALSE, ...) { 
  
  res <- object$fvec 
  
  N <- length(res) 
  
  val <-  -N * (log(2 * pi) + 1 - log(N) + log(sum(res^2)))/2 
  
  ## the formula here corresponds to estimating sigma^2. 
  
  attr(val, "df") <- 1L + length(coef(object)) 
  
  attr(val, "nobs") <- attr(val, "nall") <- N 
  
  class(val) <- "logLik" 
  
  val 
  
}
#********************************* data fitting ******************************

.args <- c("preProcessed/Hypopharynx_data.rds")

.args <- commandArgs(trailingOnly = TRUE)

#load the data and calculate the population weights in each class
FittedData <- readRDS(.args[1])
#incidenceData <- readRDS("preProcessed/StomachCancer_data.rds")
cancer <- gsub(".*preProcessed/\\s*|_data.rds*", "", .args)

#initial values for fitting
inits <- list(mu=30, tau=0.0023962, delta = 0.0047962); a <- c(0,1e-7,0.0005); b <- c(100,1, 1)
prevfits <- readRDS(paste0("fits/model3fits/",cancer,".rds")[1])
inits$tau <- unname(prevfits["tau"])
inits$mu <- unname(prevfits["mu.mu"])
inits$delta <- unname(prevfits["beta"])


obs <- FittedData$y/ max(FittedData$y)
#fitting after normalising
fit <- nls.lm(par = inits, lower = a, upper = b,
              fn = residFun, mdl = f, fxdParms = prs, observed = obs, t = FittedData$x,
              control = nls.lm.control(nprint=1,  ftol = 1e-2))

prdctns <- getPred(f, FittedData$x, fit$par, prs)




#Calculating R^2
Rsquare <- (cor(log(obs),log(prdctns)))^2

#Calculating AIC
perfom <- 2 * (length(fit$par) + 1) - 2 * logL(fit)

fitResults <- c(delta = fit$par$delta, mu = fit$par$mu, tau = fit$par$tau, AIC = perfom, Rsqr = Rsquare)

saveRDS(fitResults, paste0("fits/model3fits/",cancer,".rds")[1])

jpeg(paste0('figures/model3Figs/', cancer,'.jpg'))

age <- FittedData$x
logObs <- log10(obs)
preds <- log10(prdctns)
plot(age, logObs,  col = "blue",
     xlab = "Age", ylab = bquote('log'[10]*' Incidence'),type = "p",pch =17,
     main = bquote(bold(paste(.(cancer) ," with ",beta[t]))))
lines(age, preds, col = "red", lwd = 3)

#anotating the graph
vertSpan <- range(logObs)
least <- vertSpan[1]
space <- (vertSpan[2]-vertSpan[1])/15
#text(70, least + 5*space, paste('\nAIC = ', round(perfom,4), '\nRSS=' , round(fit$deviance,4),  pos = 4)) 
#paste("Mean =", round(MyMean, 1), "\nMedian =", round(MyMedian, 1), "\nStd.Dev =", round(MySd, 1)), pos = 4)

text(70, (least ), cex = 1.2, bquote(paste(tau, '=' , .(round(fit$par$tau,6)))))
text(70, (least + 1*space), cex = 1.2, bquote(paste(mu, '=' , .(round(fit$par$mu,4)))))
text(70, (least + 2*space), cex = 1.2, bquote(paste(delta, '=' , .(round(fit$par$delta,4)))))
text(70, (least + 3*space), cex = 1.2, expression(bold('Parameters')))
text(70, (least + 4*space), cex = 1.2, bquote(paste('RSS=' , .(round(fit$deviance,6)))))
text(70, (least + 5*space), cex = 1.2, bquote(paste('R'^2*' = ', .(round(Rsquare^2,5)))))
text(70, (least + 6*space), cex = 1.2, bquote(paste('AIC = ', .(round(perfom,4)))))
text(70, (least + 7*space), cex = 1.2, expression(bold('Performance')))

dev.off()

